FROM mhart/alpine-node:15

WORKDIR /usr/local

COPY package*.json ./

RUN npm install && npm cache clean --force

WORKDIR /usr/local/app

COPY . .

EXPOSE 3000

ENTRYPOINT ["sh", "/usr/local/app/entrypoint.sh"]