version: "3.7"

services:
  ui:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    ports:
      - 3000:3000