version: "3.7"

volumes:
  node_modules:

services:
  ui:
    container_name: erp-ui-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules